### ISSUE TITLE
Easy to solve issue - Status of activator for the rooms not working

### ISSUE THREAD

**Issue by AndyNew2** [kodebach/hacs-idm-heatpump#123]
Easy to fix issue:

When heatpump is in cooling mode used together with NavigatorPro with Zonemodules, the activator monitor do not work.
I see in the "information - Zonemodules" the Status for each "Antrieb" is 2 instead of the documented 1. 
It seems they now destinguish between activating the motor because of heating (1) or cooling (2). 
So just allow both values 1 and 2 and everything should be fine. I try to find myself the place and try it and upload the changes needed.

**Comment by AndyNew2** [comment]
In file sensor_addresses.py
line 112 ff:
    def decode(self, decoder: BinaryPayloadDecoder) -> tuple[bool, bool]:
        """Decode this sensor's value."""
        value = decoder.decode_16bit_uint()
        LOGGER.debug("raw value (uint16) for %s: %d", self.name, value)
        return (True, value == 1)

I would change to:
    def decode(self, decoder: BinaryPayloadDecoder) -> tuple[bool, bool]:
        """Decode this sensor's value."""
        value = decoder.decode_16bit_uint()
        LOGGER.debug("raw value (uint16) for %s: %d", self.name, value)
        return (True, value >= 1)

This is Python Syntax I have problems. So it return True when the condition after the value given is true, correct?
In in case it is not correct, it automatically return False? I would have written in the last line 
  return (value>=1)       
This is C, C++ logic, I am not so familar with Python.

I still need to learn Python. I can't test in the moment, since cooling is off. Will try tomorrow and report if this solves the issue.

Anyhow I fear you do not like my change and do it properly by changing the sensor type to Enum instead Binary?

**Comment by AndyNew2** [comment]
Could test it today. Modification works as expected. I would be happy to change it that way.

**Comment by kodebach** [comment]
Which sensor is this issue about? The integration does not provide an "Antrieb" sensor. For zone modules there are only two binary sensors: "Entfeuchtungsausgang" and "Relais".

**Comment by AndyNew2** [comment]
Hoffe das kommt an. der ganz normale Status Wert des Antriebs, das das Zonenmodul liefert. Der ist ja schon implementiert nur zeigt er aus beim kühlen an, obwohl der Stellmotor angesteuert ist. Die Navigator Beschreibung für ModbusTCP ist hier auch falsch. Sie beschreibt nur ein boolean für den Status des Antriebs. in Wirklichkeit ist es ein enum mit0 aus1 ein heizen2 ein kühlen Viele GrüßeAndreas WeitlAm 01.09.24, 13:48 schrieb "Klemens Böswirth" ***@***.***>:

  
  Which sensor is this issue about? The integration does not provide an "Antrieb" sensor. For zone modules there are only two binary sensors: "Entfeuchtungsausgang" and "Relais".

**Comment by kodebach** [comment]
Ich habe leider kein Zonenmodul und weiß daher nicht welcher Statuswert für den Antrieb gemeint ist. Wie bereits erwähnt, stellt die Integration nur zwei Binäre/Boolean Sensoren zur Verfügung. Diese heißen standardmäßig "Zonenmodul X Raum Y Entfeuchtungsausgang" und "Zonenmodul X Raum Y Relais"

**Comment by AndyNew2** [comment]
ah der Relais ist gemeint. Zonenmodul X Raum Y Relais.laut Doku boolean, ist aber falschhat drei Werte wie vorhin beschrieben. Viele GrüßeAndreas WeitlAm 01.09.24, 16:49 schrieb "Klemens Böswirth" ***@***.***>:

  
  Ich habe leider kein Zonenmodul und weiß daher nicht welcher Statuswert für den Antrieb gemeint ist. Wie bereits erwähnt, stellt die Integration nur zwei Binäre/Boolean Sensoren zur Verfügung. Diese heißen standardmäßig "Zonenmodul X Raum Y Entfeuchtungsausgang" und "Zonenmodul X Raum Y Relais"

**Comment by kodebach** [comment]
Bitte teste `v0.9.0-beta.2`, die "Relais" Sensoren sollten jetzt auch 2 als "an" akzeptieren

**Comment by AndyNew2** [comment]
OK mach ich, komme erst wieder Donnerstag nach Hause, dann berichte ich...Viele GrüßeAndreas WeitlAm 01.09.24, 17:35 schrieb "Klemens Böswirth" ***@***.***>:

  
  Bitte teste v0.9.0-beta.2, die "Relais" Sensoren sollten jetzt auch 2 als "an" akzeptieren

**Comment by AndyNew2** [comment]
Tried Beta 6 and did not work. I can't write anymore PV values. I got following error logs:
2024-09-08 10:37:30.055 ERROR (MainThread) [homeassistant.components.automation.idm_waermepumpe_pv_schreiben] IDM_Waermepumpe_PV_schreiben: Error executing script. Error for call_service at pos 2: Must acknowledge risk to call set_power
2024-09-08 10:37:30.056 ERROR (MainThread) [homeassistant.components.automation.idm_waermepumpe_pv_schreiben] Error while executing automation automation.idm_waermepumpe_pv_schreiben: Must acknowledge risk to call set_power

No idea what that risk means...

**Comment by kodebach** [comment]
This got a bit lost do to the various issues with getting the beta release to work at all, but it is explained in the [original release notes](https://github.com/kodebach/hacs-idm-heatpump/releases/tag/v0.9.0-beta.1). You now have to set an additional field `acknowledge_risk: true`, because incorrectly using some of the now exposed writable registers (e.g. the target room temperature ones) can cause issues and users should read IDMs documentation first.

**Comment by AndyNew2** [comment]
Ah,good idea, how or in which file do i set this value?Just once in configuration.yaml or each script using the write service? How is the syntax? If it is necessary in each script, I propose just to enforce this risk bit for really dangerous writes.The PV value write neither has a relation to flash memory (write cycle is not limited), not does the write harm the heatpump.Am 08.09.24, 13:04 schrieb "Klemens Böswirth" ***@***.***>:

  
  This got a bit lost do to the various issues with getting the beta release to work at all, but it is explained in the original release notes. You now have to set an additional field acknowledge_risk: true, because incorrectly using some of the now exposed writable registers (e.g. the target room temperature ones) can cause issues and users should read IDMs documentation first.

**Comment by kodebach** [comment]
Very few (if any) registers are actually _dangerous_ to write, even the flash memory issue only occurs for every excessive write behaviour. But almost all registers can cause issues, if not used properly. For the target room temperature registers, the documentation says that changing the value resets the zone module and doing that often can cause issues with the calculations. For the PV values there is less risk, but it could still cause unexpected behaviour, e.g. if you have an error in your HA config and your value for "PV-Überschuss" is inverted (negative and positive values swapped).

So I decided to just require the field everywhere. It also makes the code much easier.

> in which file do i set this value?

You have to pass the field for every service call, just like the value and the target entity. Where you set this depends on how you are using the service. Just open the [Developer tools in HA](https://my.home-assistant.io/redirect/developer_services/) and under "Actions" you can try out the services from this integration. The UI mode should make it show you a checkbox for the new field and switching to YAML mode shows you the YAML syntax.

It should be something like:

```yaml
action: idm_heatpump.set_power
target: # your target
data:
  value: # your value
  acknowledge_risk: true
```

**Comment by AndyNew2** [comment]
Tried now with this hint the beta 0.9.0 beta 6. Everything works as expected. Concratulations. Also this issue is fixed and can be closed.
