### ISSUE TITLE
Momentanleistung cuts out regularly

### ISSUE THREAD

**Issue by kodebach** [kodebach/hacs-idm-heatpump#134]
@kodebach is it a general issue? for me „momentanleistung“ is always dead after starting any idm process… heating… cooling…

<img width="1092" alt="image" src="https://github.com/user-attachments/assets/10b41300-1ccc-4880-b181-ae9bbe8bd109">

_Originally posted by @simowNgithub in https://github.com/kodebach/hacs-idm-heatpump/issues/126#issuecomment-2323166131_

**Comment by daemonenstall** [comment]
For me it's working fine.
![IMG_20240907_135945.jpg](https://github.com/user-attachments/assets/614bd4d7-7599-4b23-8dcf-18eaa7fcdce3)

**Comment by AndyNew2** [comment]
For me as well, @daemonenstall these are way to much cycles for the heatpump. You had 2 hot water cycles and 6 cooling cycles?
Your settings are not great @kodebach  move this to discussion so we can sort out the high cycle rate...

**Comment by daemonenstall** [comment]
The first hot water cycle is triggered by solar excess and the second one is the daily morning cycle.

**Comment by simowNgithub** [comment]
Hi guys and sorry for my late response...
I tried to fully reset my sensors and integration. I also used the newest version of kodebach. I can not tell why, but this fixed the issue... So we can close.
