### ISSUE TITLE
service set_room_mode not working for sensor.####_betriebsart_heizkreis_[abcd]

### ISSUE THREAD

**Issue by Jueff** [kodebach/hacs-idm-heatpump#142]
## Bug, missing feature or user error?
When trying to set heating mode for sensors sensor.[.*]_betriebsart_heizkreis_[abcd] the integration returns
_"Entity sensor.warmepumpe_betriebsart_heizkreis_b does not support this service."_

```yaml
service: idm_heatpump.set_room_mode
data:
  target: sensor.warmepumpe_betriebsart_heizkreis_b
  value: eco
  acknowledge_risk: true

**Comment by Jueff** [comment]
just seen the ciructe sensor use "CircuitMode" enum, not "RoomMode"

**Comment by kodebach** [comment]
Yes, the values for these sensors (Modbus registers) are slightly different, so they need different enums. Setting `CircuitMode` is currently not implemented and haven't found a way to better filter the entities shown by Home Assistant for each service.

For now I added `set_circuit_mode` to #50, but I'm not sure, when I'll get round to implementing it. I'd gladly accept a PR.
