### ISSUE TITLE
Easy to fix: Holiday Mode missing in SystemStatus

### ISSUE THREAD

**Issue by AndyNew2** [kodebach/hacs-idm-heatpump#152]
Very easy thing for next release. Not really relevant for use.
When setting the heatpump to "Holiday" mode with a few days, the Integration shows "Unknown" or "Unbekannt" for the entity:
sensor.idm_warmepumpe_betriebsart_system
That is very easy to fix (verified):

Add in const.py about line 121 the following line:
    HOLIDAY = 3

It is missing in the ModbusTCP manuel from IDM but it works that way.
It might fail to set, but the reading is fine. Not tried yet the set, since it needs also the number of days of holiday, which you can't give with the modbus request.

Only good for monitoring ;-)
[const.py.txt](https://github.com/user-attachments/files/17530973/const.py.txt)

**Comment by Jueff** [comment]
I think it will also need changes in 
services.yaml - add holiday in set_system_status.fields.value.selector.select.options: **- holiday**
de.json 
        "system_status_options": {
                "holiday": "Urlaub",

and en.json
        "system_status_options": {
                "holiday": "Holiday",

**Comment by Jueff** [comment]
created pull request #153

**Comment by Jueff** [comment]
Writing 3 to 1005 sets the heatpump to "Holiday" mode with 0 days. 
Maybe the write should be prohibited.

**Comment by AndyNew2** [comment]
What is the result in the heatpump with 0 days. Would it stay forever in holiday mode or does it immediately return to automatic?

Anyhow I do not think it is dangerous, but if it automatically returns to mode automatic, it is useless, so I would not show that option in the selection. If the heatpump stays in holiday mode, I think it is useful. Because you can use HA to control the holiday mode and switch it on, off when you need...

**Comment by Jueff** [comment]
Wrting the register is not the intention, the idea of enhancing the enum is a different one. Currently the status is shown as "unknown" if I set the heatpump to holiday mode, using the IDM userinterface.

More detail on setting modus register to "3: holiday": In case of "holiday 0 days" the mode changes to "away" after some time, maybe at daychange.
