### ISSUE TITLE
Custom component conflicts with HomeAssistant's modbus integration.

### ISSUE THREAD

**Issue by DNKROZ** [kodebach/hacs-idm-heatpump#2]
First and foremost, thank you for this custom component, it's very useful and the install is a breeze (only need to enable ModBus capabilities on the heatpump), great work.

However I did find this issue when I tried to enable Modbus integration with Home Assistant:

## Version of the custom_component

VERSION = "0.0.1"

## Configuration

```yaml

NA

```

## Describe the bug
Using this custom component with Home Assistant's modbus integration enables results in the custom component not being able to load, since both use pymodbus library but version 3.1.3 for Home Assistant and version 2.5.3 for this custom component.

Forcing this custom component to use pymodbus 3.1.3 fails, since it seems to be using some calls and/or dependencies that are no longer supported in this version.

## Debug log

```text

Logger: homeassistant.setup
Source: setup.py:213
First occurred: 1:53:52 PM (1 occurrences)
Last logged: 1:53:52 PM

Setup failed for custom integration idm_heatpump: Unable to import component: No module named 'pymodbus.client.asynchronous'

```

**Comment by kodebach** [comment]
Thanks for reporting the issue. Seems it only affected new installations so I didn't notice it.

Everything should be fixed in the new v0.2.0 release. It should now also be easier to install this custom integration via HACS. Take a look at the new README.
