### ISSUE TITLE
Missing parameters

### ISSUE THREAD

**Issue by kodebach** [kodebach/hacs-idm-heatpump#42]
There are a few internal Parameters missing in the iDM integration. 
B2 Durchflußsensor Heizung
B71 Heißgastemperatur 1
B86 Kondensationsdruck 1

These are all quite important parameters, always good to have a view on and see wrong developments. Could you add them to the integration?

_Originally posted by @AndyNew2 in https://github.com/kodebach/hacs-idm-heatpump/issues/34#issuecomment-1770913585_

**Comment by kodebach** [comment]
My documentation for Modbus from IDM doesn't show list these parameters. @AndyNew2 If you have other documentation please tell me what it says for these parameters.

**Comment by AndyNew2** [comment]
Actually you are right. I can't find them in my docu neiter. Crazy! These are key parameters very important to keep an eye on it, and especially this ones are not available on the interfaces. The same on KNX. I really don't understand why people like iDM, they crazy things.
I will try to contact iDM service. I case you do not know, the difference from Vorlauftemperatur and Heißgastemperatur should not be above 30°C. The higher the differenz the less efficient the pump is.
Furthermore it shall not reach 100°C, this is checked of course by the heatpump itself, however it is always good to know how close you got. 
For the "Durchflußsensor" I know not all heatpumps have it, but it is a further critical parameter. It shall never drop below 6 l/min. Also a parameter you want to know how close you come to that...

**Comment by AndyNew2** [comment]
Ah according the issue, this needs to wait, until supported by iDM. There is nothing to read of course, which had not been made available. The only other chance, if iDM will not help is to analyse the Windows program iDM provides. This one has all paramters included also the ones I mentioned. This had been the reason, I expected them on ModbusTCP as well. I thought this windows program uses the same interface. This is unfortunately not the case.

**Comment by AndyNew2** [comment]
I just imagine another option without iDM support. But this is a little bit effort. We could use the web interface to iDM heatpump. The mentioned values are available via HTTP on http://<local_IP_heatpump>/#/settings/3,2,1,/details
The returned page holds the desired values...

**Comment by kodebach** [comment]
I don't think the Windows App uses ModbusTCP. (1) AFAIK it only works after you log in, which indicates there using something that supports authentication, but more importantly (2) It works without enabling Modbus on the heat pump. 

Regarding the HTTP idea: I don't want to mix that into this integration. (1) I have no interest in parsing HTML that isn't meant for automated reading (2) AFAIK the local heatpump interface page only works with Javascript enable, which makes the whole thing almost impossible anyway. (3) Even the more machine readable endpoints used by the interface (*) can't easily be accessed, because they need non-trivial authentication.

If you do find an HTTP endpoint, that can be accessed easily, I recommend trying the standard integration for [simple HTTP requests](https://www.home-assistant.io/integrations/rest_command/).


(*) They still return HTML data with a JSON envelope, so not exactly machine readable.

**Comment by AndyNew2** [comment]
Agree, and it would be a lot of work as well. Just noticed the Windows iDM App don't have these values anyway. Quite surprising, but this path seems not being a help.
The HTTP request returns just the frame and not the desired data inside. This path is difficult either. This is the result of this structured pages. Deeper anylsis needed to find actually the desired values. In any case this could be done via HTTP request function available as stated.
So I propose to keep this request around a month open to see if iDM responds. The chance is low they do, typically they ignore such requests and I know why they do so.
So it is up to you, you can close it straight away as well.

**Comment by AndyNew2** [comment]
iDM answered as expected. You can't talk anymore to the people in Austria, they are all inpossible to contact. They always route you straight away to local service providers or sellers. So the answer was of course nonsense and the reality is no, they will not update the ModbusTCP implementation. iDM gots really kind of arrogant, since there is no way to propose and contact the core team, even with a kind of 2nd level support. They are untouchable...

**Comment by kodebach** [comment]
ok in that case, let's just close this issue
