### ISSUE TITLE
IDM_Wärmepumpe: Status Ladepumpe shows wrong values

### ISSUE THREAD

**Issue by AndyNew2** [kodebach/hacs-idm-heatpump#43]
Just spotted a new issue, but this maybe dependent on my heatpump as well.
The status of "Ladepumpe" shows a unit %  which is correct.
When the heatpump runs, it shows 100% and that seems to be correct. However it runs sometimes at a lower speed (for checking the heat circuits) and if the heatpump is off it should be 0%.
However everything else than 100% is shown as "Unbekannt" and therefore I can't see the correct values.
In the iDM menu there is a value -1 shown, when it is off. 
Probably something to have an eye on. 
Can you give me a hint, how to gather the raw values for this entry?

**Comment by kodebach** [comment]
Currently the raw values are only visible in the debug logs from `pymodbus` as the raw register values. To enable the debug logs follow the steps in https://github.com/kodebach/hacs-idm-heatpump/issues/34#issuecomment-1772489415. 

However, there seems to be something weird with this value. I do see values other than 0% or 100%, but there are also sometimes weird gaps where the value is missing.

**Comment by AndyNew2** [comment]
Actually I have gaps. So either is 100% or empty in the graph. I see the value "Unbekannt" in the list.

I spottet a further parameter with wrong intepretation. It is "IDM_Wärmepumpe: Status Verdichter 1". It shows OK when heatpump is off. However it shows "Problem" when the heatpump is currently running. Goes back to OK, when heatpump stops. In iDM no error or problems logged.

I will do the debug session again. However the "Unbekannt" for the Status Ladepumpe should be already in the post from #34.

**Comment by AndyNew2** [comment]
I just checked the docu, it says for Status Ladepumpe either 100% (so value 100) or -1. However I don't know how they represent -1. It seems no other values are officially supported. Let's see what the debug gives...

For Status Verdicher 1 it has just 0 = Off (Aus) and 1 = On (Ein). Maybe the description "Problem" is just wrong and should be "Ein". And "OK" should be "Aus"?

**Comment by kodebach** [comment]
Everything here should be fixed release `v0.4.0`. I also added better debug logging to the integration itself, so configuring `pymodbus` shouldn't be needed in the future.
