### ISSUE TITLE
incorrect value for sensor.idm_warmepumpe_status_ladepumpe

### ISSUE THREAD

**Issue by AndyNew2** [kodebach/hacs-idm-heatpump#56]
The value for Status Ladepumpe shows just -1 and 100 and no other values. However my heatpump iPump A3-11 supports values in between and uses it. I see in the Navigator GUI e.g. a value of 80 (80%) while it still shows me -1 in the integration.
This might be intended however I didn't really understood the description for this value. I guessed it should have 80 in that case.

**Comment by kodebach** [comment]
First of all I split this into two issues. See also #57.

Regarding "Status Ladepumpe": It should always show the same value as the Navigator GUI. If it does not, please provide debug logs. However, I'm not sure what I could do here, there is no special processing happening for this sensor, it just shows that value that we get over Modbus.

**Comment by AndyNew2** [comment]
probably there is just -1 and 100 over modbus. I need to wait until the heatpump is in that state and provide a log.

**Comment by kodebach** [comment]
I just checked and my heat pump is currently reporting 60. So probably yours only reports -1 or 100. Maybe a bug in the IDM firmware and we may have different versions.

**Comment by AndyNew2** [comment]
Interesting, sure there is nothing I need to do in the integration?
My software version is 20.22-252-g46df5882c. You think an update would fix it?

**Comment by AndyNew2** [comment]
@daemonenstall would be interesting to see what values you can see...

**Comment by daemonenstall** [comment]
![Screenshot_2023-11-12-20-06-42-339_io homeassistant companion android](https://github.com/kodebach/hacs-idm-heatpump/assets/69319145/99057c1f-7b57-4398-bd36-2a36e4c20119)

**Comment by kodebach** [comment]
> nothing I need to do in the integration?

Please provide debug logs, when the Navigator UI is showing something other than -1 or 100. Then I can double check what is sent via Modbus by the heat pump.

> My software version is 20.22-252-g46df5882c. You think an update would fix it?

Mine says `s_20.23-19-gdb55e4e94`, which looks newer, so an update might help. But I'm not sure you can update the firmware yourself. I think IDM has to do that.

**Comment by daemonenstall** [comment]
When I look at this description in the webinterface, I think the pump is not modulating. There is only off or 100%, nothing in between. When I look at the values of the smart meter before the pump, I would say that this is plausible.
![Screenshot_2023-11-12-20-11-30-631_at idm_energie android](https://github.com/kodebach/hacs-idm-heatpump/assets/69319145/50bf46c1-43af-45d5-808b-195232d98dc5)

**Comment by daemonenstall** [comment]
Ok, I have found a value other then -1 or 100%.
![IMG_20231112_202759](https://github.com/kodebach/hacs-idm-heatpump/assets/69319145/1e7cb911-f034-4f31-8505-8016fbe309f1)

**Comment by kodebach** [comment]
> When I look at this description in the webinterface, I think the pump is not modulating.

@AndyNew2 said in the top post here, that he has seen the value 80 in the Navigator interface, so at least in his case the pump seems to be modulating.

I've also seen other values, although I have an Aero SLM heat pump not an iPump.

> Ok, I have found a value other than -1 or 100%.

No that's just Home Assistant calculating an average value between two real values. If you click "Mehr anzeigen" to open the full history page for the sensor, you'll see the real values and in your case it seems there is only -1 and 100.

**Comment by daemonenstall** [comment]
You are right, there is only -1 and 100. I should not write answers from my cell phone.

**Comment by AndyNew2** [comment]
Just to clarify, this could be configured on the service level of the heatpump. If it just allows 100% you do not see anything different. However I configured 80% as the minimum and whenever the heatpump is off but the rooms wants heating this is the value activated for the pump.

**Comment by AndyNew2** [comment]
Hi, it took longer to get this log. Sorry I always missed the spot during the day. Now I got it. The "Ladepumpe" is according IDM GUI at 60% (that was the value configured as minimum in the settings). However the integration shows still -1 instead of 60. See attached the log. Hopefully there is useful information.
[home-assistant_idm_heatpump_2023-11-18T09-30-54.103Z.log](https://github.com/kodebach/hacs-idm-heatpump/files/13399902/home-assistant_idm_heatpump_2023-11-18T09-30-54.103Z.log)

**Comment by kodebach** [comment]
In the logs the value sent via Modbus is always -1. Can you check if using the new "Sensoren einzeln laden" option fixes the issue? Otherwise, I don't really know what I could do to fix this...

**Comment by AndyNew2** [comment]
Yes will try and report. The issue is, I am always too late at home to see that situation. Probably tomorrow I will be able to log it and try it...

**Comment by AndyNew2** [comment]
Got more details now. I reduced my max value from 100% to 95% and see: Now the integration shows 95%. It seems it only works when the compressor runs. In times the compressor is off, but the circulation pump is on it still shows -1. Need to observe it in more details, but that what I see in the moment. But I need to give the information, I have now a newer firmware installed.

Anyway I always see either max value or min value for the "Ladepumpe". I never detected a value in between. I have now configured 50% and 95%. Interestingwise in hot water generation or defrost, it still goes to 100%. But that is consistent to the values I see in the integration. Only the min value as a kind of preparation before the compressor starts seems to be ignored.

**Comment by kodebach** [comment]
What do you see in the list from #69 (ID 1104)? If those values match what Home Assistant shows, there is nothing I can do here

**Comment by AndyNew2** [comment]
I got it now. You are right, even in the GLT Monitor in IDM GUI it shows -1 in that case. That means the value for the Ladepumpe is not communicated via ModbusTCP, when the compressor is off, and it always communicates -1, even the "Ladepumpe" works at it's minimum value as a preparation for heating. (You could force your heatpump in that state by blocking with Smart Grid EVU Sperre and having a situation the heatpump wants to start....
Check with your settings in Service-Level für the minimum value for the "Ladepumpe". 

So according my observations, this issue can be closed, because there is nothing could be done in that integration.

I wanted to slowly setup a web parser to get out this value and a lot more. I know now it is PHP controlled and there is a frame with all this nice values. However to get the communication running, you need to convince the heatpump you set a Cookie and have the right CSRF token with you. Unfortunately my tries with Multiscrape failed till now. If anybody has experience tipps, everything welcome.

**Comment by kodebach** [comment]
> Unfortunately my tries with Multiscrape failed till now. If anybody has experience tipps, everything welcome.

Yeah, I think you'd need some custom integration code to perform proper authentication flow.

> So according my observations, this issue can be closed, because there is nothing could be done in that integration.

Agreed, you could also try asking IDM about it. I would assume the fact that it reports -1 even though the pump is running is an oversight in the firmware

**Comment by AndyNew2** [comment]
I had my bugreport limit already reached this year ;-) 
Maybe next year...
