### ISSUE TITLE
Loads of very useful ModbusTCP parameters, like a dream

### ISSUE THREAD

**Issue by AndyNew2** [kodebach/hacs-idm-heatpump#69]
By chance I dedected a bunch of new parameters in the ModbusTCP description for the IDM heatpump. This should give us a lot more possibilities:
You can check the values and addresses yourself by activating the "Service-Ebene", and then 
Service - Gebäudeleittechnik - GLT Monitor

In here you see following new, (not yet described) parameters, even some of them for writing:

- ID 76 Leistung E-Heizstab, RW reading and writing, not sure what is that for
- ID 82 Hausverbrauch RW, that may activate us the statistics in the IDM GUI, worth to try
- ID 84 Batterieentladung RW
- ID 86 Batterie Füllstand RW ,,, All this values may give us the activation of IDM statistics, I want to try...

and now the very important parameters:

- ID 4108 Leistungsbegrenzung Wärmepumpe RW, o my God, this is the desired value; I need this to write. I lack of the unit, but guess kW, because all other power values are in kW.
- ID 4112 Leistungsbegrenzung Kaskade RW, no I do not have a "Kaskade" but may be useful for somebody.
- ID 4124 elektrische Gesamtleistung, no idea why it is there again, worth to check. will observe and report. Probably only if you have a Kaskade
- ID 4126 thermische Leistung no idea why this is there again, the original ID was 1790

I think the ID 4108 Leistungsbegrenzung and ID 82, 84 and 86 are gamechangers...

**Comment by kodebach** [comment]
Interesting, I will take a look as soon as I find some time to work on the integration.

**Comment by AndyNew2** [comment]
I could not wait and activiated my old modbus writing script. 
It actually works and you get a lot more details in the IDM GUI. In the previous ModbusTCP integration you just had seen the overproduction and based on that, the heatpump activation more activities.
With the additional parameters, you got a full Photovoltaik-Integration in IDM. You see the battery, if you have one and your house power. Actually writing these values had been a little bit tricky, since I expected the usage differently.

So here my findings:

ID 76 Leistung E-Heizstab, RW reading and writing, not sure what is that for
   ... not tried, no idea what it is good for. Anybody an idea?

ID 82 Hausverbrauch RW, 
   Yes this is a float value, will be written like all other kW values for the PV production. Unit is kW. 
   This is actually the consuption including the heatpump. What the IDM GUI does, it substracts its own power consuption from that value and assigns the rest to the house. Be caseful to set this value including the consuption of the heatpump, since otherwise it reduces the power from its own consuption and the house consuption is 0.

ID 84 Batterieentladung RW
   Is just used for the GUI and nice to see. It is not part of any IDM calculation, just used for statistics. Value is again a float in in kW
ID 86 Batterie Füllstand RW
  This is an integer value (I just passed the value without converting to float). I think -1 is interpreted not to have a battery, and it will be removed from display and statistics. Otherwise it is the SOC (state of charge) in %. So valid parameters are from 0 to 100.
The very great thing is, once writing these values, there appear a lot more settings in the IDM GUI. You have now the possiblity to specify a minimum battery level for setting PV mode in IDM. Not exactly understood, how this works, but these values activates a lot more statistics and values in the IDM GUI. Really nice. 
Have fun and I look forward to have it integrated here...

**Comment by kodebach** [comment]
> ID 76 Leistung E-Heizstab, RW reading and writing, not sure what is that for

Most (if not all) heat pumps have a resistive heating element to assist the actual heat pump in very cold weather (e.g. -10°C). So I guess reading the value tells you whether the heating element is in use. It is in kW and not a simple on/off value, since some IDM models (including mine) have multiple heating elements with different resistances (and therefore wattage), so the heat output can be regulated better.

Not sure what writing would do. Maybe you can manually enable the heating element, maybe it just limits the power, who knows. Without documentation, I don't think I will support writing this value in the integration.

> ID 82 Hausverbrauch RW,
> ID 84 Batterieentladung RW
> ID 86 Batterie Füllstand RW

I added them to #50

**Comment by Krasto82** [comment]
yes exactly, I use the parameter of the battery with the excess of solar power. If I have surplus and the SOC is at least 30% I run an additional domestic hot water load for example.

**Comment by Krasto82** [comment]
> Interesting, I will take a look as soon as I find some time to work on the integration.

By calling id86 I can correctly see the INT value of the battery charge. Great and trying it works

**Comment by Krasto82** [comment]
Great work. I will delete my modbus sensors to see soc percentage. Thanks

**Comment by AndyNew2** [comment]
I will try, but I assume no change. Maybe that is linked to a special contract for your grid provider? Maybe a smart grid contract needs to be active? I am just guessing...

**Comment by AndyNew2** [comment]
Just checked my previous tries. I already did what you proposed. So I have written 1200.0 to that register, without any success. Still ignored and nothing shown in the GLT Monitor. Further ideas?

**Comment by kodebach** [comment]
> Further ideas?

Nope sorry, you'll have to ask IDM how that parameter works.

**Comment by AndyNew2** [comment]
Correct and thanks for support. I asked my iDM support today, to ask iDM the question about that parameters. My hope is very low they give an reasonable answer, as everything I asked till now, including detailed bug reports had been ignored. iDM no longer is touchable for customers, .... Let's see maybe we got surprised ;-)

**Comment by AndyNew2** [comment]
I got a response, but the expected one. These parameters are only for iDM themselves. Nothing a user should know about.

Of course, thanks iDM for not helping us, like nowadays always....

**Comment by AndyNew2** [comment]
Ah this issue can be closed, nothing else to do here...

**Comment by Krasto82** [comment]
New upgrade for IDM navigator

[Release Notes_Nav_2.0_en.pdf](https://github.com/kodebach/hacs-idm-heatpump/files/14230494/Release.Notes_Nav_2.0_en.pdf)

**Comment by AndyNew2** [comment]
Cool Krasto82, where you got this document from? Do you have a reasonable contact to iDM, or you found it on internet?

**Comment by AndyNew2** [comment]
@Krasto82 Very interested in the source.

**Comment by Krasto82** [comment]
> Cool Krasto82, where you got this document from? Do you have a reasonable contact to iDM, or you found it on internet?

The pdf was shared with me by my installer. He told me that idm always sends a changelog to them when they release a new firmware

**Comment by AndyNew2** [comment]
Did you got more files, or just the description file? The company name of the installer is Nothaft or a different company?

**Comment by Krasto82** [comment]
Only this file, the installer updated the firmware via OTA. Company Name of the installer is Valsolar located in Italy.

**Comment by AndyNew2** [comment]
Ah finally a different contact. Will they forward requests to iDM? How helpful are they? I struggly a little bit with my contacts...

**Comment by Krasto82** [comment]
> Ah finally a different contact. Will they forward requests to iDM? How helpful are they? I struggly a little bit with my contacts...

they are a local company and are in contact with idm italia.
If you want I'll leave you their website
https://valsolar.eu/
