### ISSUE TITLE
HA Core 2025.1 deprecation

### ISSUE THREAD

**Issue by IgneaX** [kodebach/hacs-idm-heatpump#71]
Hi,
At first i want to say thank you for your great work!

After updating to 2024.1.0 i get the information in the logs that the Unit parameters will deprecate in 2025.

ENERGY_KILO_WATT_HOUR was used from idm_heatpump, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfEnergy.KILO_WATT_HOUR instead, please create a bug report at https://github.com/kodebach/hacs-idm-heatpump/issues
POWER_KILO_WATT was used from idm_heatpump, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfPower.KILO_WATT instead, please create a bug report at https://github.com/kodebach/hacs-idm-heatpump/issues
TEMP_CELSIUS was used from idm_heatpump, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please create a bug report at https://github.com/kodebach/hacs-idm-heatpump/issues

**Comment by kodebach** [comment]
Yes, I saw that too. Hopefully I'll find some time this week to address this and some of the other open issues...
